"""add learning phase 3 models

Revision ID: 37f0b8c56d5c
Revises: 
Create Date: 2026-03-27 18:42:15.721292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37f0b8c56d5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.alter_column('badges', 'condition_value',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('ix_badges_name'), table_name='badges')
    op.create_unique_constraint(None, 'badges', ['name'])
    op.drop_column('badges', 'updated_at')
    op.add_column('course_materials', sa.Column('knowledge_graph_id', sa.Integer(), nullable=True))
    op.add_column('course_materials', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('course_materials', sa.Column('order_num', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_materials', 'knowledge_graphs', ['knowledge_graph_id'], ['id'], ondelete='SET NULL')
    op.drop_column('course_materials', 'duration_seconds')
    op.add_column('courses', sa.Column('level', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('cover_url', sa.String(), nullable=True))
    op.drop_constraint(op.f('courses_knowledge_graph_id_fkey'), 'courses', type_='foreignkey')
    op.drop_column('courses', 'knowledge_graph_id')
    op.create_foreign_key(None, 'interview_sessions', 'users', ['candidate_id'], ['id'])
    op.drop_constraint(op.f('knowledge_graphs_parent_id_fkey'), 'knowledge_graphs', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_graphs', 'knowledge_graphs', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('idx_permissions_name'), table_name='permissions')
    op.drop_index(op.f('idx_permissions_resource'), table_name='permissions')
    op.drop_constraint(op.f('permissions_name_key'), 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.alter_column('questions', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_roles_name'), table_name='roles')
    op.drop_index(op.f('idx_roles_parent'), table_name='roles')
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_index(op.f('idx_sms_verifications_phone'), table_name='sms_verifications')
    op.create_index(op.f('ix_sms_verifications_id'), 'sms_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_sms_verifications_phone'), 'sms_verifications', ['phone'], unique=False)
    op.add_column('user_badges', sa.Column('tx_hash', sa.String(), nullable=True))
    op.drop_column('user_badges', 'blockchain_hash')
    op.add_column('user_question_collections', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_constraint(op.f('user_question_collections_question_id_fkey'), 'user_question_collections', type_='foreignkey')
    op.create_foreign_key(None, 'user_question_collections', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_wrong_questions', sa.Column('answer_count', sa.Integer(), nullable=True))
    op.add_column('user_wrong_questions', sa.Column('is_mastered', sa.Boolean(), nullable=True))
    op.add_column('user_wrong_questions', sa.Column('last_answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('user_wrong_questions_question_id_fkey'), 'user_wrong_questions', type_='foreignkey')
    op.create_foreign_key(None, 'user_wrong_questions', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_wrong_questions', 'error_count')
    op.drop_column('user_wrong_questions', 'last_error_at')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_phone'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_practice_questions_id'), table_name='practice_questions')
    op.drop_table('practice_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.add_column('user_wrong_questions', sa.Column('last_error_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('user_wrong_questions', sa.Column('error_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_wrong_questions', type_='foreignkey')
    op.create_foreign_key(op.f('user_wrong_questions_question_id_fkey'), 'user_wrong_questions', 'practice_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_wrong_questions', 'last_answered_at')
    op.drop_column('user_wrong_questions', 'is_mastered')
    op.drop_column('user_wrong_questions', 'answer_count')
    op.drop_constraint(None, 'user_question_collections', type_='foreignkey')
    op.create_foreign_key(op.f('user_question_collections_question_id_fkey'), 'user_question_collections', 'practice_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_question_collections', 'notes')
    op.add_column('user_badges', sa.Column('blockchain_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_badges', 'tx_hash')
    op.drop_index(op.f('ix_sms_verifications_phone'), table_name='sms_verifications')
    op.drop_index(op.f('ix_sms_verifications_id'), table_name='sms_verifications')
    op.create_index(op.f('idx_sms_verifications_phone'), 'sms_verifications', ['phone'], unique=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_roles_parent'), 'roles', ['parent_id'], unique=False)
    op.create_index(op.f('idx_roles_name'), 'roles', ['name'], unique=False)
    op.alter_column('questions', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.create_unique_constraint(op.f('permissions_name_key'), 'permissions', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_index(op.f('idx_permissions_name'), 'permissions', ['name'], unique=False)
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.drop_constraint(None, 'knowledge_graphs', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_graphs_parent_id_fkey'), 'knowledge_graphs', 'knowledge_graphs', ['parent_id'], ['id'])
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.add_column('courses', sa.Column('knowledge_graph_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('courses_knowledge_graph_id_fkey'), 'courses', 'knowledge_graphs', ['knowledge_graph_id'], ['id'], ondelete='SET NULL')
    op.drop_column('courses', 'cover_url')
    op.drop_column('courses', 'level')
    op.add_column('course_materials', sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course_materials', type_='foreignkey')
    op.drop_column('course_materials', 'order_num')
    op.drop_column('course_materials', 'duration')
    op.drop_column('course_materials', 'knowledge_graph_id')
    op.add_column('badges', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'badges', type_='unique')
    op.create_index(op.f('ix_badges_name'), 'badges', ['name'], unique=True)
    op.alter_column('badges', 'condition_value',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_table('practice_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('knowledge_graph_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('correct_answer', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], name=op.f('practice_questions_job_position_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_graph_id'], ['knowledge_graphs.id'], name=op.f('practice_questions_knowledge_graph_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('practice_questions_pkey'))
    )
    op.create_index(op.f('ix_practice_questions_id'), 'practice_questions', ['id'], unique=False)
    # ### end Alembic commands ###
